// <auto-generated />
namespace NewsAppMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedDateCreatedfromTopicsclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedDateCreatedfromTopicsclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201802051854100_removed DateCreated from Topics class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
