// <auto-generated />
namespace NewsAppMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datepickertoarticleandtopic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datepickertoarticleandtopic));
        
        string IMigrationMetadata.Id
        {
            get { return "201801072248415_date picker to article and topic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
