// <auto-generated />
namespace NewsAppMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addaccessorstotopicsviewmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addaccessorstotopicsviewmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201801120201378_add accessors to topics viewmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
